import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { PaginationProvider } from "./contexts/usePagination";
import { SearchFilterProvider } from "./contexts/useSearchFilter";
import { ComboboxValuesProvider } from "./contexts/useComboboxValues";
import { ThemeProvider } from "./providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-background min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PaginationProvider>
            <SearchFilterProvider>
              <ComboboxValuesProvider>{children}</ComboboxValuesProvider>
            </SearchFilterProvider>
          </PaginationProvider>
        </ThemeProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
